In [1]:
import pandas as pd
import datetime
import numpy as np

In [21]:
df = pd.read_csv ('C:/Users/Vincent/Desktop/pws_user.csv', header=None)
df.insert(1, '',df[0] )
df = df.T
df.columns = df.iloc[0]
df = df[1:].T
pd.options.display.max_rows = 100
df.index.name = None
df.columns = ['Password']
df

            Password
b06302238  b06302238
b08106047  b08106047
b05102097  b05102097
b06302345  b06302345
b06102085  b06102085
b09613010  b09613010
b07605042  b07605042
b07610040  b07610040
b07610044  b07610044
b06202064  b06202064
b07104024  b07104024
b06106021  b06106021
b09609020  b09609020
b08207013  b08207013
b01504125  b01504125
b09a01258  b09a01258
r09722007  r09722007
r09848012  r09848012
b07704059  b07704059
b06105045  b06105045
b07605036  b07605036
b06702079  b06702079
b09607004  b09607004
b08106048  b08106048
b09203070  b09203070
b06302326  b06302326
b09611033  b09611033
b07102007  b07102007
b08705027  b08705027
b04102044  b04102044
b08106040  b08106040
r08627021  r08627021
b09704076  b09704076
b06701138  b06701138
b06302352  b06302352
b07310007  b07310007
b06505044  b06505044
b09207049  b09207049
b09611028  b09611028
b06701153  b06701153
b08109021  b08109021
r09741063  r09741063
b08705028  b08705028
b08705003  b08705003
b08106009  b08106009
b07502043  b07502043
b09a01115  b09a01115
b09305013  b09305013
b06703042  b06703042
b06310033  b06310033
b06507028  b06507028
b07501013  b07501013
b06204046  b06204046
b06702055  b06702055
b06502026  b06502026
b07801014  b07801014
b06404030  b06404030
b05602046  b05602046
b08207080  b08207080
b08403006  b08403006
b06703017  b06703017
b06b02054  b06b02054
b07207003  b07207003
b09606006  b09606006
b07303053  b07303053
b06303103  b06303103
b07704043  b07704043
b06404008  b06404008
b08401111  b08401111
b07303091  b07303091
b09201001  b09201001
b09704027  b09704027
b06404003  b06404003
r08322046  r08322046
b06702026  b06702026
r09322020  r09322020
b06201049  b06201049
b06705012  b06705012
b07705031  b07705031
b06703012  b06703012
b08303051  b08303051
b09605029  b09605029
b06502168  b06502168

In [5]:
#C:/Users/jiaojiaozhe/Desktop/PWS HW1.csv
df = pd.read_csv ('C:/Users/Vincent/Desktop/ff/PWS.csv', header = None,
                 names=['When','ID','Status','Problem','Time', 'Memory', 'Language',
                        'Author', 'HW'], converters={'Problem': lambda x: str(x),
                        'HW': lambda x: '-'.join(x.split())})
df['Problem'] = '0' + df['HW'].apply(lambda x:x[-1])  #+ df['Problem'].apply(lambda x: x[-2:])
df['When'] = df['When'].apply(lambda x:x.replace('-', '/'))
pd.set_option('display.max_rows', 10)
df

IndexError: string index out of range

In [3]:
df.sort_values(['Problem', 'Author', 'When'], inplace = True)
df.head(20)
#整理過的資料

                    When            ID            Status Problem     Author
1072 2021-03-09 17:18:11  b837d1d8c2b6      Wrong Answer    0101  b01504125
1066 2021-03-09 17:27:16  2cdad30c7902  Partial Accepted    0101  b01504125
1060 2021-03-09 18:00:08  9e4af91216a9  Partial Accepted    0101  b01504125
1049 2021-03-09 20:05:37  e7a9637d93f7  Partial Accepted    0101  b01504125
1046 2021-03-09 20:11:42  8489711158fc     Compile Error    0101  b01504125
1045 2021-03-09 20:12:07  d0e7f933342a  Partial Accepted    0101  b01504125
1042 2021-03-09 20:14:45  b0d60f27cbf5  Partial Accepted    0101  b01504125
1041 2021-03-09 20:17:45  2c80f60ee1bd          Accepted    0101  b01504125
1285 2021-03-08 10:26:45  f553dcd897bd  Partial Accepted    0101  b04102044
1216 2021-03-08 12:22:52  ae59b10fbb1b  Partial Accepted    0101  b04102044
1199 2021-03-08 16:32:06  15d8cb7bbb2d  Partial Accepted    0101  b04102044
1193 2021-03-08 17:46:20  bb2d8592c9e4  Partial Accepted    0101  b04102044
956  2021-03-10 08:36:33  7c97d5dde682  Partial Accepted    0101  b04102044
955  2021-03-10 08:38:27  b1f97dc93173          Accepted    0101  b04102044
2466 2021-02-25 01:34:30  bd53bc1d9be6  Partial Accepted    0101  b05102097
2464 2021-02-25 01:36:29  c444dc582374  Partial Accepted    0101  b05102097
2662 2021-02-24 15:21:55  3e02e75f46ab      Wrong Answer    0101  b05602046
2661 2021-02-24 15:23:59  24c473ce3a8f  Partial Accepted    0101  b05602046
2660 2021-02-24 15:26:06  25e4dcc5bdd4  Partial Accepted    0101  b05602046
2659 2021-02-24 15:31:30  7abf869e1232  Partial Accepted    0101  b05602046

In [4]:
me = df[(df['Author'] == 'b06703012') & (df['Status'] == 'Accepted')]
me = me.T
me.columns = range(1,11)
me

,1,2,3,4,5,6,7,8,9,10
When,2021-03-10 20:15:12,2021-02-26 21:39:13,2021-02-26 21:57:21,2021-02-26 22:41:15,2021-02-26 23:09:13,2021-02-27 00:35:10,2021-03-10 20:10:59,2021-03-11 02:01:17,2021-03-10 20:42:20,2021-03-10 20:34:10
ID,c89bf2ce95ed,6a5af42931f9,f9fbc53e8d8f,a84a2107643f,e506e04e7306,3db0d5421620,920ad205e5dc,a3ff5dc6b056,999e5f15ed86,9d39d814fec7
Status,Accepted,Accepted,Accepted,Accepted,Accepted,Accepted,Accepted,Accepted,Accepted,Accepted
Problem,01,0101,0102,0103,0104,0105,02,03,04,05
Author,b06703012,b06703012,b06703012,b06703012,b06703012,b06703012,b06703012,b06703012,b06703012,b06703012

In [5]:
authors = df['Author'].unique()
authors.sort()
#學生id
problems_id = df['Problem'].unique()
problems_id.sort()
#問題id
len(authors)

82

In [6]:
problem_types = df.groupby(['Author', 'Problem', 'Status'])['Status'].size().rename('Status_Total').reset_index()
problem_types
#分項繳交次數

         Author Problem            Status  Status_Total
0     b01504125      01          Accepted             1
1     b01504125    0101          Accepted             1
2     b01504125    0101     Compile Error             1
3     b01504125    0101  Partial Accepted             5
4     b01504125    0101      Wrong Answer             1
...         ...     ...               ...           ...
1180  r09848012      03     Compile Error             1
1181  r09848012      03     Runtime Error             1
1182  r09848012      03      Wrong Answer             2
1183  r09848012      04          Accepted             1
1184  r09848012      05          Accepted             1

[1185 rows x 4 columns]

In [7]:
problem_total = df.groupby(['Author', 'Problem'])['Status'].size().rename('Total_Submit_Times').reset_index()
problem_total
#總繳交次數

        Author Problem  Total_Submit_Times
0    b01504125      01                   1
1    b01504125    0101                   8
2    b01504125    0102                   7
3    b01504125    0103                   8
4    b01504125    0104                  17
..         ...     ...                 ...
657  r09848012    0105                   1
658  r09848012      02                   1
659  r09848012      03                   7
660  r09848012      04                   1
661  r09848012      05                   1

[662 rows x 3 columns]

In [8]:
problems_info = pd.merge(problem_types, problem_total, left_on = ['Author', 'Problem'], right_on = ['Author', 'Problem'])
problems_info
#上面兩個合併

         Author Problem            Status  Status_Total  Total_Submit_Times
0     b01504125      01          Accepted             1                   1
1     b01504125    0101          Accepted             1                   8
2     b01504125    0101     Compile Error             1                   8
3     b01504125    0101  Partial Accepted             5                   8
4     b01504125    0101      Wrong Answer             1                   8
...         ...     ...               ...           ...                 ...
1180  r09848012      03     Compile Error             1                   7
1181  r09848012      03     Runtime Error             1                   7
1182  r09848012      03      Wrong Answer             2                   7
1183  r09848012      04          Accepted             1                   1
1184  r09848012      05          Accepted             1                   1

[1185 rows x 5 columns]

In [9]:
accepted = problems_info[problems_info["Status"] == "Accepted"]
accepted.sort_values('Status_Total')
accepted.head(100)

        Author Problem    Status  Status_Total  Total_Submit_Times
0    b01504125      01  Accepted             1                   1
1    b01504125    0101  Accepted             1                   8
5    b01504125    0102  Accepted             1                   7
8    b01504125    0103  Accepted             2                   8
10   b01504125    0104  Accepted             1                  17
13   b01504125    0105  Accepted             1                   3
15   b01504125      02  Accepted             1                   1
16   b01504125      03  Accepted             1                   1
17   b01504125      04  Accepted             1                   2
19   b01504125      05  Accepted             1                   1
20   b04102044      01  Accepted             1                   2
22   b04102044    0101  Accepted             1                   6
24   b04102044    0102  Accepted             1                  12
28   b04102044    0103  Accepted             1                   9
32   b04102044    0104  Accepted             1                   5
34   b04102044    0105  Accepted             1                   3
36   b04102044      02  Accepted             1                   1
37   b04102044      03  Accepted             1                   1
38   b04102044      04  Accepted             1                   1
39   b04102044      05  Accepted             1                   1
41   b05602046      01  Accepted             1                   1
42   b05602046    0101  Accepted             1                   7
45   b05602046    0102  Accepted             1                   1
46   b05602046    0103  Accepted             1                   2
48   b05602046    0104  Accepted             1                   3
50   b05602046    0105  Accepted             1                   3
52   b05602046      02  Accepted             1                   1
53   b05602046      03  Accepted             1                   6
56   b05602046      04  Accepted             1                   1
57   b05602046      05  Accepted             1                   1
58   b06102085    0101  Accepted             1                  14
62   b06105045      01  Accepted             1                   4
65   b06105045    0102  Accepted             1                   1
68   b06105045    0105  Accepted             1                   1
69   b06105045      02  Accepted             1                   1
70   b06105045      03  Accepted             1                   1
71   b06105045      04  Accepted             1                   1
72   b06105045      05  Accepted             1                   2
74   b06106021    0101  Accepted             1                  29
79   b06106021    0102  Accepted             1                  31
84   b06201049      01  Accepted             1                   1
85   b06201049    0101  Accepted             1                   1
86   b06201049    0102  Accepted             1                   1
87   b06201049    0103  Accepted             1                   3
89   b06201049    0104  Accepted             1                   1
90   b06201049    0105  Accepted             1                   1
91   b06201049      02  Accepted             1                   1
92   b06201049      03  Accepted             1                   2
94   b06201049      04  Accepted             1                   1
95   b06201049      05  Accepted             1                   1
96   b06204046      01  Accepted             1                   1
97   b06204046    0101  Accepted             1                  10
100  b06204046    0102  Accepted             1                   3
102  b06204046    0103  Accepted             1                   1
103  b06204046    0104  Accepted             1                   4
105  b06204046    0105  Accepted             1                  13
108  b06204046      02  Accepted             1                   1
109  b06204046      03  Accepted             1                   1
110  b06204046      04  Accepted             1                   1
111  b06204046      05  Accepted             1                   1
116  b06302326    0101  Accepted             1                   5
119  b06302326    0102  Accepted             1                   1
123  b06302326    0105  Accepted             1                   6
125  b06302352      01  Accepted             1                   1
126  b06302352    0101  Accepted             1                  11
130  b06302352    0102  Accepted             1                   1
136  b06302352    0105  Accepted             1                   5
139  b06302352      02  Accepted             1                   2
142  b06303103      01  Accepted             1                   1
143  b06303103    0101  Accepted             1                   1
144  b06303103    0102  Accepted             1                   1
145  b06303103    0103  Accepted             2                   2
146  b06303103    0104  Accepted             2                  29
148  b06303103    0105  Accepted             1                   2
150  b06303103      02  Accepted             1                   1
151  b06303103      03  Accepted             1                   3
153  b06303103      04  Accepted             1                   1
154  b06303103      05  Accepted             1                   1
155  b06310033    0101  Accepted             1                   9
159  b06310033    0102  Accepted             1                   7
162  b06310033    0103  Accepted             1                  14
165  b06310033    0104  Accepted             1                  39
169  b06310033    0105  Accepted             1                   2
171  b06404003      01  Accepted             1                   1
172  b06404003    0101  Accepted             1                   1
173  b06404003    0102  Accepted             1                   1
174  b06404003    0103  Accepted             1                   1
175  b06404003    0104  Accepted             2                   5
178  b06404003    0105  Accepted             1                   2
180  b06404003      02  Accepted             1                   1
181  b06404003      03  Accepted             1                   1
182  b06404003      04  Accepted             1                   1
183  b06404003      05  Accepted             1                   5
185  b06404008      01  Accepted             1                   1
186  b06404008    0101  Accepted             3                  18
189  b06404008    0102  Accepted             3                   4
191  b06404008    0103  Accepted             3                   6
194  b06404008    0104  Accepted             5                  46
199  b06404008    0105  Accepted            12                  18
201  b06404008      02  Accepted             1                   1

In [10]:
accepted.insert(5, 'Submit_Times_Before_AC', accepted["Total_Submit_Times"] - accepted["Status_Total"])
times_before_ac = accepted[['Author', 'Problem', 'Submit_Times_Before_AC']]
times_before_ac

         Author Problem  Submit_Times_Before_AC
0     b01504125      01                       0
1     b01504125    0101                       7
5     b01504125    0102                       6
8     b01504125    0103                       6
10    b01504125    0104                      16
...         ...     ...                     ...
1177  r09848012    0105                       0
1178  r09848012      02                       0
1179  r09848012      03                       4
1183  r09848012      04                       0
1184  r09848012      05                       0

[621 rows x 3 columns]

In [11]:
pd.set_option('display.max_rows', 100)
from_start_to_last_submit = df[['Author', 'Problem', 'When', 'Status']].sort_values(['Author', 'When'])
#from_start_to_last_submit.head(50)
#算時間的表格

In [12]:
work_time = []
for author in authors:
    for problem in problems_id:
        submit_time = from_start_to_last_submit.loc[(from_start_to_last_submit['Author'] == author) & (from_start_to_last_submit['Problem'] == problem), ['Author', 'Problem', 'When', 'Status']]
        process_time = submit_time['When'].max() - submit_time['When'].min()
        #print(author, problem, process_time)
        work_time.append([author, problem, process_time])
        
work_time.sort(key=lambda x: (x[0], x[1]))
work_time = pd.DataFrame(work_time, columns= ['Author','Problem', 'Process_Time'])
#work_time
#每人分項所花時間

In [13]:
time = pd.merge(times_before_ac, work_time, left_on = ['Author', 'Problem'], right_on = ['Author', 'Problem'])
time.sort_values('Process_Time').head(100)
#合併繳交次數與花的時間

        Author Problem  Submit_Times_Before_AC Process_Time
0    b01504125      01                       0       0 days
354  b07801014      05                       0       0 days
353  b07801014      04                       0       0 days
346  b07801014    0101                       0       0 days
345  b07801014      01                       0       0 days
344  b07705031      05                       0       0 days
343  b07705031      04                       0       0 days
342  b07705031      03                       0       0 days
341  b07705031      02                       0       0 days
337  b07705031    0102                       0       0 days
355  b08106009      01                       0       0 days
336  b07705031    0101                       0       0 days
332  b07704059    0101                       0       0 days
331  b07704043      05                       0       0 days
330  b07704043      04                       0       0 days
329  b07704043      03                       0       0 days
328  b07704043      02                       0       0 days
324  b07704043    0102                       0       0 days
322  b07704043      01                       0       0 days
318  b07610040    0102                       0       0 days
619  r09848012      04                       0       0 days
335  b07705031      01                       0       0 days
356  b08106009    0101                       0       0 days
357  b08106009    0102                       0       0 days
358  b08106009    0103                       0       0 days
406  b08303051      02                       0       0 days
405  b08303051    0105                       0       0 days
402  b08303051    0102                       0       0 days
400  b08303051      01                       0       0 days
399  b08207080      05                       0       0 days
398  b08207080      04                       0       0 days
397  b08207080      03                       0       0 days
396  b08207080      02                       0       0 days
395  b08207080    0105                       0       0 days
393  b08207080    0103                       0       0 days
389  b08207013    0105                       0       0 days
385  b08207013    0101                       0       0 days
384  b08109021      05                       0       0 days
382  b08109021      03                       0       0 days
377  b08109021      01                       0       0 days
370  b08106040    0105                       0       0 days
365  b08106040      01                       0       0 days
364  b08106009      05                       0       0 days
363  b08106009      04                       0       0 days
361  b08106009      02                       0       0 days
360  b08106009    0105                       0       0 days
304  b07502043      01                       0       0 days
408  b08303051      04                       0       0 days
302  b07501013      04                       0       0 days
300  b07501013      02                       0       0 days
237  b06b02054      02                       0       0 days
233  b06b02054    0102                       0       0 days
232  b06b02054    0101                       0       0 days
231  b06b02054      01                       0       0 days
230  b06705012      05                       0       0 days
229  b06705012      04                       0       0 days
228  b06705012      03                       0       0 days
227  b06705012      02                       0       0 days
223  b06705012    0102                       0       0 days
239  b06b02054      05                       0       0 days
221  b06705012      01                       0       0 days
219  b06703042      04                       0       0 days
218  b06703042      03                       0       0 days
217  b06703042      02                       0       0 days
214  b06703042    0103                       0       0 days
213  b06703042    0102                       0       0 days
211  b06703042      01                       0       0 days
210  b06703017      05                       0       0 days
208  b06703017      03                       0       0 days
207  b06703017      02                       0       0 days
220  b06703042      05                       0       0 days
241  b07102007    0102                       0       0 days
242  b07102007    0103                       0       0 days
243  b07102007    0104                       0       0 days
297  b07501013    0103                       0       0 days
293  b07310007      05                       0       0 days
292  b07310007      04                       0       0 days
290  b07310007      02                       0       0 days
284  b07310007      01                       0       0 days
283  b07303091      05                       0       0 days
282  b07303091      04                       0       0 days
280  b07303091      02                       0       0 days
274  b07303091      01                       0       0 days
273  b07303053      05                       0       0 days
271  b07303053      03                       0       0 days
270  b07303053      02                       0       0 days
267  b07303053    0103                       0       0 days
265  b07303053      01                       0       0 days
264  b07207003      05                       0       0 days
263  b07207003      04                       0       0 days
262  b07207003      03                       0       0 days
261  b07207003      02                       0       0 days
258  b07207003    0103                       0       0 days
255  b07207003      01                       0       0 days
247  b07104024    0102                       0       0 days
301  b07501013      03                       0       0 days
410  b08401111      01                       0       0 days
412  b08401111    0102                       0       0 days
416  b08401111      02                       0       0 days
563  b09a01258    0105                       0       0 days

In [14]:
d = {'0101':{'b06703012': '1', 'b06703042': '11'}, 
     '0201':{'b06703012': '2', 'b06703042': '12'},
      '0301':{'b06703012': '3', 'b06703042': '13'},
      '0401':{'b06703012': '4', 'b06703042': '14'},
      '0501':{'b06703012': '5', 'b06703042': '15'},
      '0601':{'b06703012': '6', 'b06703042': '16'},
      '0701':{'b06703012': '7', 'b06703042': '17'},
      '0801':{'b06703012': '8', 'b06703042': '18'},
      '0901':{'b06703012': '9', 'b06703042': '19'},
     '1001':{'b06703012': '10', 'b06703042': '20'}}
df1 = pd.DataFrame(data = d)
df1

          0101 0201 0301 0401 0501 0601 0701 0801 0901 1001
b06703012    1    2    3    4    5    6    7    8    9   10
b06703042   11   12   13   14   15   16   17   18   19   20